#!/bin/bash
#
# Install diaspora dependencies i. e., what apt-get will do
#

grep -v '^#' /etc/apt/sources.list | grep -q universe || {
    cat <<- EOF
	"Warning: it looks like you have not enabled universe in your
	/etc/apt/sources.list. Most likely, this means trouble.
	But I will try anyway.
	EOF
    sleep 2
}

sudo apt-get update
sudo apt-get install -qy build-essential libxslt1-dev libxml2 ruby-full mongodb \
     rake python-software-properties git imagemagick libmagick9-dev
sudo add-apt-repository ppa:maco.m/ruby
sudo apt-get update
sudo apt-get install -qy rubygems
sudo gem install bundler  --bindir /usr/local/bin
