#!/bin/bash
#
# Install diaspora dependencies i. e., what apt-get will do
#

grep -v '^#' /etc/apt/sources.list | grep -q universe || {
    cat <<- EOF
	"Warning: it looks like you have not enabled universe in your
	/etc/apt/sources.list. Most likely, this means trouble.
	But I will try anyway.
	EOF
    sleep 2
}
release=$( lsb_release -a | awk '/Release:/ {print $2}')

sudo apt-get update
sudo apt-get install --no-install-recommends -qy\
     build-essential libxslt1-dev  libxml2  \
     ruby-full mongodb rake python-software-properties git-core \
     imagemagick libmagick9-dev
if [ "$release" = "10.04" ]; then
    # See: https://bugs.launchpad.net/ubuntu/+source/mongodb/+bug/557024
    sudo apt-get install xulrunner-1.9
    xulversion=$( xulrunner --gre-version)
    sudo ln -sf "/usr/lib/xulrunner-$xulversion/libmozjs.so" /usr/lib
fi
sudo add-apt-repository ppa:maco.m/ruby
sudo apt-get update
sudo apt-get install -qy rubygems
sudo gem install bundler  --bindir /usr/local/bin
