#!/bin/sh
#
# Try to revert to pristine state, deleting all users and
# configuration

set -x
service mongod stop
service diaspora-ws stop
rm -rf /var/lib/mongod/*
cp /usr/share/diaspora/master/config/app_config.yml.example \
  /usr/share/diaspora/master/config/app_config.yml
service mongod start


