production:
    after_checkout:
      - source: /config/cloud/cloud66/files/database.yml
        destination: <%= ENV['STACK_PATH'] %>/config/database.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/diaspora.yml
        destination: <%= ENV['STACK_PATH'] %>/config/diaspora.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/Procfile
        destination: <%= ENV['STACK_PATH'] %>/Procfile
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/unicorn.rb.cloud66
        destination: <%= ENV['STACK_PATH'] %>/config/unicorn.rb.cloud66
        target: rails
        run_on: all_servers
    after_rails:
      #- source: /config/cloud/cloud66/scripts/seed.sh
      #  destination: /tmp/seed.sh
      #  target: rails
      #  apply_during: build_only
      #  execute: true
      #  sudo: true
      - source: /config/cloud/cloud66/scripts/redis.sh
        destination: /tmp/redis.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true
development:
    after_checkout:
      - source: /config/cloud/cloud66/files/database.yml
        destination: <%= ENV['STACK_PATH'] %>/config/database.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/diaspora.yml
        destination: <%= ENV['STACK_PATH'] %>/config/diaspora.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/Procfile
        destination: <%= ENV['STACK_PATH'] %>/Procfile
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/unicorn.rb.cloud66
        destination: <%= ENV['STACK_PATH'] %>/config/unicorn.rb.cloud66
        target: rails
        run_on: all_servers
    after_rails:
      #- source: /config/cloud/cloud66/scripts/seed.sh
      #  destination: /tmp/seed.sh
      #  target: rails
      #  apply_during: build_only
      #  execute: true
      #  sudo: true
      - source: /config/cloud/cloud66/scripts/redis.sh
        destination: /tmp/redis.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true
staging:
    after_checkout:
      - source: /config/cloud/cloud66/files/database.yml
        destination: <%= ENV['STACK_PATH'] %>/config/database.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/diaspora.yml
        destination: <%= ENV['STACK_PATH'] %>/config/diaspora.yml
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/Procfile
        destination: <%= ENV['STACK_PATH'] %>/Procfile
        target: rails
        run_on: all_servers
      - source: /config/cloud/cloud66/files/unicorn.rb.cloud66
        destination: <%= ENV['STACK_PATH'] %>/config/unicorn.rb.cloud66
        target: rails
        run_on: all_servers
    after_rails:
      #- source: /config/cloud/cloud66/scripts/seed.sh
      #  destination: /tmp/seed.sh
      #  target: rails
      #  apply_during: build_only
      #  execute: true
      #  sudo: true
      - source: /config/cloud/cloud66/scripts/redis.sh
        destination: /tmp/redis.sh
        target: rails
        apply_during: build_only
        execute: true
        sudo: true