#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3.  See
#   the COPYRIGHT file.


default:
  pod_url: "http://example.org/"
  debug: false
  socket_debug : false
  socket_host: 0.0.0.0
  socket_port: 8080
  socket_collection_name: 'websocket'
  pubsub_server: 'https://pubsubhubbub.appspot.com/'
  mongo_host: 'localhost'
  mongo_post: 27017
  
development:

test:
  pod_url: "http://example.org/"
  socket_port: 8081

production:
