script_server:
  # Choose database. Currently supported: mysql, postgres
  db: "mysql"

  # Enable thin as application server
  enable_thin: true

  # Port on which thin should listen
  thin_port: 3000

  # Customize thin's startup
  default_thin_args: "-p $THIN_PORT -e $RAILS_ENV"

  # Possibilities are development, production
  rails_env: "development"
