<% require_relative 'config/load_config' %>
---
:verbose: false
<% unless AppConfig.heroku? %>
:logfile: "<%= AppConfig.sidekiq_log %>"
<% end %>
:concurrency: <%= AppConfig.environment.sidekiq.concurrency.to_i %>
:queues:
  - urgent
  - high
  - medium
  - low
  - default
