require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KeyRingsController do

  # This should return the minimal set of attributes required to create a valid
  # KeyRing. As you add validations to KeyRing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KeyRingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all key_rings as @key_rings" do
      key_ring = KeyRing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:key_rings).should eq([key_ring])
    end
  end

  describe "GET show" do
    it "assigns the requested key_ring as @key_ring" do
      key_ring = KeyRing.create! valid_attributes
      get :show, {:id => key_ring.to_param}, valid_session
      assigns(:key_ring).should eq(key_ring)
    end
  end

  describe "GET new" do
    it "assigns a new key_ring as @key_ring" do
      get :new, {}, valid_session
      assigns(:key_ring).should be_a_new(KeyRing)
    end
  end

  describe "GET edit" do
    it "assigns the requested key_ring as @key_ring" do
      key_ring = KeyRing.create! valid_attributes
      get :edit, {:id => key_ring.to_param}, valid_session
      assigns(:key_ring).should eq(key_ring)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KeyRing" do
        expect {
          post :create, {:key_ring => valid_attributes}, valid_session
        }.to change(KeyRing, :count).by(1)
      end

      it "assigns a newly created key_ring as @key_ring" do
        post :create, {:key_ring => valid_attributes}, valid_session
        assigns(:key_ring).should be_a(KeyRing)
        assigns(:key_ring).should be_persisted
      end

      it "redirects to the created key_ring" do
        post :create, {:key_ring => valid_attributes}, valid_session
        response.should redirect_to(KeyRing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved key_ring as @key_ring" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeyRing.any_instance.stub(:save).and_return(false)
        post :create, {:key_ring => {}}, valid_session
        assigns(:key_ring).should be_a_new(KeyRing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeyRing.any_instance.stub(:save).and_return(false)
        post :create, {:key_ring => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested key_ring" do
        key_ring = KeyRing.create! valid_attributes
        # Assuming there are no other key_rings in the database, this
        # specifies that the KeyRing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KeyRing.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => key_ring.to_param, :key_ring => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested key_ring as @key_ring" do
        key_ring = KeyRing.create! valid_attributes
        put :update, {:id => key_ring.to_param, :key_ring => valid_attributes}, valid_session
        assigns(:key_ring).should eq(key_ring)
      end

      it "redirects to the key_ring" do
        key_ring = KeyRing.create! valid_attributes
        put :update, {:id => key_ring.to_param, :key_ring => valid_attributes}, valid_session
        response.should redirect_to(key_ring)
      end
    end

    describe "with invalid params" do
      it "assigns the key_ring as @key_ring" do
        key_ring = KeyRing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeyRing.any_instance.stub(:save).and_return(false)
        put :update, {:id => key_ring.to_param, :key_ring => {}}, valid_session
        assigns(:key_ring).should eq(key_ring)
      end

      it "re-renders the 'edit' template" do
        key_ring = KeyRing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeyRing.any_instance.stub(:save).and_return(false)
        put :update, {:id => key_ring.to_param, :key_ring => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested key_ring" do
      key_ring = KeyRing.create! valid_attributes
      expect {
        delete :destroy, {:id => key_ring.to_param}, valid_session
      }.to change(KeyRing, :count).by(-1)
    end

    it "redirects to the key_rings list" do
      key_ring = KeyRing.create! valid_attributes
      delete :destroy, {:id => key_ring.to_param}, valid_session
      response.should redirect_to(key_rings_url)
    end
  end

end
