#!/usr/bin/env bash
# to be included by install.sh


####                                                             ####
#                                                                   #
#                           DEFAULT VARS                            #
#                                                                   #
####                                                             ####

# list of required programs
declare -A BINARIES
BINARIES["git"]="git"
BINARIES["ruby"]="ruby"
BINARIES["rubygems"]="gem"
BINARIES["bundler"]="bundle"
BINARIES["sed"]="sed"
BINARIES["mktemp"]="mktemp"
BINARIES["dirname"]="dirname"
BINARIES["basename"]="basename"
BINARIES["realpath"]="realpath"

# local path for git clone, can be changed by the user interactively
D_GIT_CLONE_PATH="/srv/diaspora"
D_GIT_BRANCH="develop"

# a few important web addresses
D_REMOTE_REPO_URL="https://github.com/diaspora/diaspora.git"
D_WIKI_URL="https://github.com/diaspora/diaspora/wiki"

# irc url
D_IRC_URL="irc://freenode.net/diaspora"

# database config, can be changed by the user interactively
D_DB_CONFIG_FILE="config/database.yml"
D_DB="mysql"
D_DB_HOST="localhost"
D_DB_USER="diaspora"
D_DB_PASS="diaspora"


####                                                             ####
#                                                                   #
#                           INTERNAL VARS                           #
#                                                                   #
####                                                             ####

D_INSTALL_SCRIPT_URL="$D_REMOTE_BASE_URL$D_INSTALL_SCRIPT"
RVM_DETECTED=false
JS_RUNTIME_DETECTED=false
ONE_UP="\e[1A"
