#!/usr/bin/env bash
# to be included by install.sh

# read a variable defined in the remote repository
# usage:
#   read_remote_var "name_in_remote_script" "name_we_want_locally"
read_var_remote() {
  _remote_name=$1
  _local_name=$2
  _remote_source="$D_REMOTE_BASE_URL$D_REMOTE_ENV_PATH"

  eval "$_local_name=\"$(include_remote $_remote_source; echo ${!_remote_name})\""
}
