default: "en"
available:
  ar: "العربية"
  bg: "български език"
  br: "Brezhoneg"
  ca: "Català"
  cs: "Čeština"
  cy: "Cymraeg"
  da: "Dansk"
  de: "Deutsch"
  el: "Ελληνικά"
  en: "English"
  en_shaw: "𐑦𐑙𐑤𐑦𐑖"
  eo: "Esperanto"
  es: "Español"
  es-AR: "Castellano"
  es-CL: "Español Chileno"
  eu: "Euskara"
  fi: "Suomi"
  fr: "Français"
  ga: "Gaeilge"
  gl: "Galego"
  he: "עברית"
  hu: "magyar nyelv"
  id: "Bahasa Indonesia"
  is: "íslenska"  
  it: "Italiano"
  ja: "日本語"
  ko: "한국어"
  lt: "Lietuviškai"
  mk: "македонски"
  ml: "മലയാളം"
  nb: "Norske"
  nl: "Nederlands"
  pa: "ਪੰਜਾਬੀ"
  pl: "polski"
  pt-BR: "Português"
  ro: "Română"
  ru: "Русский"
  sl: "Slovenščina"
  sk: "Slovenčina"
  sv: "Svenska"
  tr: "Türk"
  zh-CN: "中文"
  zh-TW: "台灣中文"
fallbacks:
  en-GB:
    - :en
  en-US:
    - :en
  en_shaw:
    - :en
    - :en-GB
    - :en-US
  sv:
    - :sv-SE
  he:
    - :he-IL
  es-AR:
    - :es
  es-CL:
    - :es
  gl:
    - :gl-ES
  zh:
    - :zh-CN
    - :zh-TW
rtl:
  - :ar
  - :he
